# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-09 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180909_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='New Title', max_length=255),
        ),
    ]
