# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-09 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.CharField(default='draft', max_length=120),
        ),
    ]
