# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-10 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='New Title', error_messages={'unique': 'This title is not unique, please try again'}, max_length=255, unique=True, verbose_name='Post Title'),
        ),
    ]
